<?php if(!isset($v_sval)) die();?>
<?php
$v_error_message = '';
$v_mongo_id = NULL;
$v_product_id = 0;
$v_product_sku = '0';
$v_short_description = '';
$v_long_description = '';
$v_product_detail = '';
$v_size_option = 0;
$v_size_unit = '0';
$arr_size = array();
$v_image_option = 0;
$v_num_images = 0;
$v_package_quantity = 1;
$v_allow_single = 1;
$v_package_type = 0;
$arr_package_content = array();
$v_image_file = '';
$v_image_desc = '';
$v_image_choose = 0;
$v_saved_dir = '';
$arr_map_content = array();
$arr_material = array();
$v_text_option = 0;
$arr_text = array();
$v_sold_by = '';
$v_default_price = 0;
$v_product_status = 0;
$v_company_id = 0;
$v_location_id = 0;
$arr_taxonomy = array();
$arr_tag = array();
$v_product_note = '';
$v_product_threshold = -1;
$v_product_threshold_group_id = 0;
$v_excluded_location = '';
$v_file_hd = '';
$v_user_name = '';
$v_user_type = 0;
$v_date_created = date('Y-m-d H:i:s', time());
if(isset($_POST['btn_submit_tb_product'])){
	$v_mongo_id = isset($_POST['txt_mongo_id'])?$_POST['txt_mongo_id']:NULL;
	if(trim($v_mongo_id)!='') $v_mongo_id = new MongoID($v_mongo_id); else $v_mongo_id = NULL;
	$cls_tb_product->set_mongo_id($v_mongo_id);
	$v_product_id = isset($_POST['txt_product_id'])?$_POST['txt_product_id']:$v_product_id;
	if(is_null($v_mongo_id)){
		$v_product_id = $cls_tb_product->select_next('product_id');
	}
	$v_product_id = (int) $v_product_id;
	$cls_tb_product->set_product_id($v_product_id);
	$v_product_sku = isset($_POST['txt_product_sku'])?$_POST['txt_product_sku']:$v_product_sku;
	$v_product_sku = trim($v_product_sku);
	if($v_product_sku=='') $v_error_message .= '[Product Sku] is empty!<br />';
	$cls_tb_product->set_product_sku($v_product_sku);
	$v_short_description = isset($_POST['txt_short_description'])?$_POST['txt_short_description']:$v_short_description;
	$v_short_description = trim($v_short_description);
	if($v_short_description=='') $v_error_message .= '[Short Description] is empty!<br />';
	$cls_tb_product->set_short_description($v_short_description);
	$v_long_description = isset($_POST['txt_long_description'])?$_POST['txt_long_description']:$v_long_description;
	$v_long_description = trim($v_long_description);
	if($v_long_description=='') $v_error_message .= '[Long Description] is empty!<br />';
	$cls_tb_product->set_long_description($v_long_description);
	$v_product_detail = isset($_POST['txt_product_detail'])?$_POST['txt_product_detail']:$v_product_detail;
	$v_product_detail = trim($v_product_detail);
	if($v_product_detail=='') $v_error_message .= '[Product Detail] is empty!<br />';
	$cls_tb_product->set_product_detail($v_product_detail);
	$v_size_option = isset($_POST['txt_size_option'])?$_POST['txt_size_option']:$v_size_option;
	$v_size_option = (int) $v_size_option;
	if($v_size_option<0) $v_error_message .= '[Size Option] is negative!<br />';
	$cls_tb_product->set_size_option($v_size_option);
	$v_size_unit = isset($_POST['txt_size_unit'])?$_POST['txt_size_unit']:$v_size_unit;
	$v_size_unit = trim($v_size_unit);
	if($v_size_unit=='') $v_error_message .= '[Size Unit] is empty!<br />';
	$cls_tb_product->set_size_unit($v_size_unit);
	$arr_size = isset($_POST['txt_size'])?$_POST['txt_size']:$arr_size;
	$cls_tb_product->set_size($arr_size);
	$v_image_option = isset($_POST['txt_image_option'])?$_POST['txt_image_option']:$v_image_option;
	$v_image_option = (int) $v_image_option;
	if($v_image_option<0) $v_error_message .= '[Image Option] is negative!<br />';
	$cls_tb_product->set_image_option($v_image_option);
	$v_num_images = isset($_POST['txt_num_images'])?$_POST['txt_num_images']:$v_num_images;
	$v_num_images = (int) $v_num_images;
	if($v_num_images<0) $v_error_message .= '[Num Images] is negative!<br />';
	$cls_tb_product->set_num_images($v_num_images);
	$v_package_quantity = isset($_POST['txt_package_quantity'])?$_POST['txt_package_quantity']:$v_package_quantity;
	$v_package_quantity = (int) $v_package_quantity;
	if($v_package_quantity<0) $v_error_message .= '[Package Quantity] is negative!<br />';
	$cls_tb_product->set_package_quantity($v_package_quantity);
	$v_allow_single = isset($_POST['txt_allow_single'])?$_POST['txt_allow_single']:$v_allow_single;
	$v_allow_single = (int) $v_allow_single;
	if($v_allow_single<0) $v_error_message .= '[Allow Single] is negative!<br />';
	$cls_tb_product->set_allow_single($v_allow_single);
	$v_package_type = isset($_POST['txt_package_type'])?$_POST['txt_package_type']:$v_package_type;
	$v_package_type = (int) $v_package_type;
	if($v_package_type<0) $v_error_message .= '[Package Type] is negative!<br />';
	$cls_tb_product->set_package_type($v_package_type);
	$arr_package_content = isset($_POST['txt_package_content'])?$_POST['txt_package_content']:$arr_package_content;
	$cls_tb_product->set_package_content($arr_package_content);
	$v_image_file = isset($_POST['txt_image_file'])?$_POST['txt_image_file']:$v_image_file;
	$v_image_file = trim($v_image_file);
	if($v_image_file=='') $v_error_message .= '[Image File] is empty!<br />';
	$cls_tb_product->set_image_file($v_image_file);
	$v_image_desc = isset($_POST['txt_image_desc'])?$_POST['txt_image_desc']:$v_image_desc;
	$v_image_desc = trim($v_image_desc);
	if($v_image_desc=='') $v_error_message .= '[Image Desc] is empty!<br />';
	$cls_tb_product->set_image_desc($v_image_desc);
	$v_image_choose = isset($_POST['txt_image_choose'])?$_POST['txt_image_choose']:$v_image_choose;
	$v_image_choose = (int) $v_image_choose;
	if($v_image_choose<0) $v_error_message .= '[Image Choose] is negative!<br />';
	$cls_tb_product->set_image_choose($v_image_choose);
	$v_saved_dir = isset($_POST['txt_saved_dir'])?$_POST['txt_saved_dir']:$v_saved_dir;
	$v_saved_dir = trim($v_saved_dir);
	if($v_saved_dir=='') $v_error_message .= '[Saved Dir] is empty!<br />';
	$cls_tb_product->set_saved_dir($v_saved_dir);
	$arr_map_content = isset($_POST['txt_map_content'])?$_POST['txt_map_content']:$arr_map_content;
	$cls_tb_product->set_map_content($arr_map_content);
	$arr_material = isset($_POST['txt_material'])?$_POST['txt_material']:$arr_material;
	$cls_tb_product->set_material($arr_material);
	$v_text_option = isset($_POST['txt_text_option'])?$_POST['txt_text_option']:$v_text_option;
	$v_text_option = (int) $v_text_option;
	if($v_text_option<0) $v_error_message .= '[Text Option] is negative!<br />';
	$cls_tb_product->set_text_option($v_text_option);
	$arr_text = isset($_POST['txt_text'])?$_POST['txt_text']:$arr_text;
	$cls_tb_product->set_text($arr_text);
	$v_sold_by = isset($_POST['txt_sold_by'])?$_POST['txt_sold_by']:$v_sold_by;
	$v_sold_by = trim($v_sold_by);
	if($v_sold_by=='') $v_error_message .= '[Sold By] is empty!<br />';
	$cls_tb_product->set_sold_by($v_sold_by);
	$v_default_price = isset($_POST['txt_default_price'])?$_POST['txt_default_price']:$v_default_price;
	$v_default_price = (float) $v_default_price;
	if($v_default_price<0) $v_error_message .= '[Default Price] is negative!<br />';
	$cls_tb_product->set_default_price($v_default_price);
	$v_product_status = isset($_POST['txt_product_status'])?$_POST['txt_product_status']:$v_product_status;
	$v_product_status = (int) $v_product_status;
	if($v_product_status<0) $v_error_message .= '[Product Status] is negative!<br />';
	$cls_tb_product->set_product_status($v_product_status);
	$v_company_id = isset($_POST['txt_company_id'])?$_POST['txt_company_id']:$v_company_id;
	$v_company_id = (int) $v_company_id;
	if($v_company_id<0) $v_error_message .= '[Company Id] is negative!<br />';
	$cls_tb_product->set_company_id($v_company_id);
	$v_location_id = isset($_POST['txt_location_id'])?$_POST['txt_location_id']:$v_location_id;
	$v_location_id = (int) $v_location_id;
	if($v_location_id<0) $v_error_message .= '[Location Id] is negative!<br />';
	$cls_tb_product->set_location_id($v_location_id);
	$arr_taxonomy = isset($_POST['txt_taxonomy'])?$_POST['txt_taxonomy']:$arr_taxonomy;
	$cls_tb_product->set_taxonomy($arr_taxonomy);
	$arr_tag = isset($_POST['txt_tag'])?$_POST['txt_tag']:$arr_tag;
	$cls_tb_product->set_tag($arr_tag);
	$v_product_note = isset($_POST['txt_product_note'])?$_POST['txt_product_note']:$v_product_note;
	$v_product_note = trim($v_product_note);
	if($v_product_note=='') $v_error_message .= '[Product Note] is empty!<br />';
	$cls_tb_product->set_product_note($v_product_note);
	$v_product_threshold = isset($_POST['txt_product_threshold'])?$_POST['txt_product_threshold']:$v_product_threshold;
	$v_product_threshold = (int) $v_product_threshold;
	if($v_product_threshold<0) $v_error_message .= '[Product Threshold] is negative!<br />';
	$cls_tb_product->set_product_threshold($v_product_threshold);
	$v_product_threshold_group_id = isset($_POST['txt_product_threshold_group_id'])?$_POST['txt_product_threshold_group_id']:$v_product_threshold_group_id;
	$v_product_threshold_group_id = (int) $v_product_threshold_group_id;
	if($v_product_threshold_group_id<0) $v_error_message .= '[Product Threshold Group Id] is negative!<br />';
	$cls_tb_product->set_product_threshold_group_id($v_product_threshold_group_id);
	$v_excluded_location = isset($_POST['txt_excluded_location'])?$_POST['txt_excluded_location']:$v_excluded_location;
	$v_excluded_location = trim($v_excluded_location);
	if($v_excluded_location=='') $v_error_message .= '[Excluded Location] is empty!<br />';
	$cls_tb_product->set_excluded_location($v_excluded_location);
	$v_file_hd = isset($_POST['txt_file_hd'])?$_POST['txt_file_hd']:$v_file_hd;
	$v_file_hd = trim($v_file_hd);
	if($v_file_hd=='') $v_error_message .= '[File Hd] is empty!<br />';
	$cls_tb_product->set_file_hd($v_file_hd);
	$v_user_name = isset($_POST['txt_user_name'])?$_POST['txt_user_name']:$v_user_name;
	$v_user_name = trim($v_user_name);
	if($v_user_name=='') $v_error_message .= '[User Name] is empty!<br />';
	$cls_tb_product->set_user_name($v_user_name);
	$v_user_type = isset($_POST['txt_user_type'])?$_POST['txt_user_type']:$v_user_type;
	$v_user_type = (int) $v_user_type;
	if($v_user_type<0) $v_error_message .= '[User Type] is negative!<br />';
	$cls_tb_product->set_user_type($v_user_type);
	$v_date_created = isset($_POST['txt_date_created'])?$_POST['txt_date_created']:$v_date_created;
	if(!check_date($v_date_created)) $v_error_message .= '[Date Created] is invalid date/time!<br />';
	$cls_tb_product->set_date_created($v_date_created);
	if($v_error_message==''){
		if(is_null($v_mongo_id)){
			$v_mongo_id = $cls_tb_product->insert();
			$v_result = is_object($v_mongo_id);
		}else{
			$v_result = $cls_tb_product->update(array('_id' => $v_mongo_id));
		}
		if($v_result) redir(URL.$v_admin_key);
	}
}else{
	$v_product_id= isset($_GET['id'])?$_GET['id']:'0';
	settype($v_product_id,'int');
	if($v_product_id>0){
		$v_row = $cls_tb_product->select_one(array('product_id' => $v_product_id));
		if($v_row == 1){
			$v_mongo_id = $cls_tb_product->get_mongo_id();
			$v_product_id = $cls_tb_product->get_product_id();
			$v_product_sku = $cls_tb_product->get_product_sku();
			$v_short_description = $cls_tb_product->get_short_description();
			$v_long_description = $cls_tb_product->get_long_description();
			$v_product_detail = $cls_tb_product->get_product_detail();
			$v_size_option = $cls_tb_product->get_size_option();
			$v_image_option = $cls_tb_product->get_image_option();
			$v_num_images = $cls_tb_product->get_num_images();
			$v_package_quantity = $cls_tb_product->get_package_quantity();
			$v_allow_single = $cls_tb_product->get_allow_single();
			$v_package_type = $cls_tb_product->get_package_type();
			$arr_package_content = $cls_tb_product->get_package_content();
			$v_image_file = $cls_tb_product->get_image_file();
			$v_image_desc = $cls_tb_product->get_image_desc();
			$v_image_choose = $cls_tb_product->get_image_choose();
			$v_saved_dir = $cls_tb_product->get_saved_dir();
			$arr_map_content = $cls_tb_product->get_map_content();
			$arr_material = $cls_tb_product->get_material();
			$v_text_option = $cls_tb_product->get_text_option();
			$arr_text = $cls_tb_product->get_text();
			$v_sold_by = $cls_tb_product->get_sold_by();
			$v_default_price = $cls_tb_product->get_default_price();
			$v_product_status = $cls_tb_product->get_product_status();
			$v_company_id = $cls_tb_product->get_company_id();
			$v_location_id = $cls_tb_product->get_location_id();
			$arr_tag = $cls_tb_product->get_tag();
			$v_product_note = $cls_tb_product->get_product_note();
			$v_product_threshold = $cls_tb_product->get_product_threshold();
			$v_product_threshold_group_id = $cls_tb_product->get_product_threshold_group_id();
			$v_excluded_location = $cls_tb_product->get_excluded_location();
			$v_file_hd = $cls_tb_product->get_file_hd();
			$v_user_name = $cls_tb_product->get_user_name();
			$v_user_type = $cls_tb_product->get_user_type();
			$v_date_created = date('Y-m-d H:i:s',$cls_tb_product->get_date_created());
		}
	}
}
$v_company_id = isset($_POST['txt_company_id'])?$_POST['txt_company_id']:(isset($v_company_id)?$v_company_id:'0');
settype($v_company_id, 'int');
$v_dsp_company_option = $cls_tb_company->draw_option('company_id', 'company_name', $v_company_id);
?>