<?php if(!isset($v_sval)) die();?>
<?php
if(isset($_SESSION['ss_location_where_clause'])){
	$v_where_clause = $_SESSION['ss_tb_order_where_clause'];
	$arr_where_clause = unserialize($v_where_clause);
}
if(!isset($arr_where_clause) || !is_array($arr_where_clause)) $arr_where_clause = array();
if(isset($_SESSION['ss_tb_order_sort'])){
	$v_sort = $_SESSION['ss_tb_order_sort'];
	$arr_sort = unserialize($v_sort);
}
if(!isset($arr_sort) || !is_array($arr_sort)) $arr_sort = array();
$arr_tb_order = $cls_tb_order->select($arr_where_clause, $arr_sort);
$v_dsp_tb_order = '<table class="list_table" width="100%" cellpadding="3" cellspacing="0" border="0" align="center">';

$v_dsp_tb_order .= '<tr align="center" valign="middle">';
$v_dsp_tb_order .= '<th>Ord</th>';
$v_dsp_tb_order .= '<th>Order Id</th>';
$v_dsp_tb_order .= '<th>Raw Id</th>';
$v_dsp_tb_order .= '<th>Anvy Id</th>';
$v_dsp_tb_order .= '<th>Location Id</th>';
$v_dsp_tb_order .= '<th>Company Id</th>';
$v_dsp_tb_order .= '<th>Po Number</th>';
$v_dsp_tb_order .= '<th>Order Type</th>';
$v_dsp_tb_order .= '<th>Shipping Contact</th>';
$v_dsp_tb_order .= '<th>Total Order Amount</th>';
$v_dsp_tb_order .= '<th>Total Discount</th>';
$v_dsp_tb_order .= '<th>Billing Contact</th>';
$v_dsp_tb_order .= '<th>Net Order Amount</th>';
$v_dsp_tb_order .= '<th>Gross Order Amount</th>';
$v_dsp_tb_order .= '<th>Job Description</th>';
$v_dsp_tb_order .= '<th>Description</th>';
$v_dsp_tb_order .= '<th>Notes</th>';
$v_dsp_tb_order .= '<th>Order Ref</th>';
$v_dsp_tb_order .= '<th>Sale Rep</th>';
$v_dsp_tb_order .= '<th>Date Created</th>';
$v_dsp_tb_order .= '<th>Date Required</th>';
$v_dsp_tb_order .= '<th>Date Approved</th>';
$v_dsp_tb_order .= '<th>Date Modified</th>';
$v_dsp_tb_order .= '<th>Term</th>';
$v_dsp_tb_order .= '<th>Delivery Method</th>';
$v_dsp_tb_order .= '<th>Source</th>';
$v_dsp_tb_order .= '<th>Status</th>';
$v_dsp_tb_order .= '<th>Require Approved</th>';
$v_dsp_tb_order .= '<th>User Approved</th>';
$v_dsp_tb_order .= '<th>User Modified</th>';
$v_dsp_tb_order .= '<th>User Name</th>';
$v_dsp_tb_order .= '<th>Dispatch</th>';
$v_dsp_tb_order .= '<th>Tax 1</th>';
$v_dsp_tb_order .= '<th>Tax 2</th>';
$v_dsp_tb_order .= '<th>Tax 3</th>';
$v_dsp_tb_order .= '</tr>';
$v_count = 1;
foreach($arr_tb_order as $arr){
	$v_dsp_tb_order .= '<tr align="left" valign="middle">';
	$v_dsp_tb_order .= '<td align="right">'.($v_count++).'</td>';
	$v_order_id = isset($arr['order_id'])?$arr['order_id']:0;
	$v_raw_id = isset($arr['raw_id'])?$arr['raw_id']:'';
	$v_anvy_id = isset($arr['anvy_id'])?$arr['anvy_id']:'';
	$v_location_id = isset($arr['location_id'])?$arr['location_id']:0;
	$v_company_id = isset($arr['company_id'])?$arr['company_id']:0;
	$v_po_number = isset($arr['po_number'])?$arr['po_number']:'';
	$v_order_type = isset($arr['order_type'])?$arr['order_type']:0;
	$v_shipping_contact = isset($arr['shipping_contact'])?$arr['shipping_contact']:'';
	$v_total_order_amount = isset($arr['total_order_amount'])?$arr['total_order_amount']:0;
	$v_total_discount = isset($arr['total_discount'])?$arr['total_discount']:0;
	$v_billing_contact = isset($arr['billing_contact'])?$arr['billing_contact']:'';
	$v_net_order_amount = isset($arr['net_order_amount'])?$arr['net_order_amount']:0;
	$v_gross_order_amount = isset($arr['gross_order_amount'])?$arr['gross_order_amount']:0;
	$v_job_description = isset($arr['job_description'])?$arr['job_description']:'';
	$v_description = isset($arr['description'])?$arr['description']:'';
	$v_notes = isset($arr['notes'])?$arr['notes']:'';
	$v_order_ref = isset($arr['order_ref'])?$arr['order_ref']:'';
	$v_sale_rep = isset($arr['sale_rep'])?$arr['sale_rep']:'';
	$v_date_created = isset($arr['date_created'])?$arr['date_created']:(new MongoDate(time()));
	$v_date_required = isset($arr['date_required'])?$arr['date_required']:(new MongoDate(time()));
	$v_date_approved = isset($arr['date_approved'])?$arr['date_approved']:(new MongoDate(time()));
	$v_date_modified = isset($arr['date_modified'])?$arr['date_modified']:(new MongoDate(time()));
	$v_term = isset($arr['term'])?$arr['term']:0;
	$v_delivery_method = isset($arr['delivery_method'])?$arr['delivery_method']:0;
	$v_source = isset($arr['source'])?$arr['source']:0;
	$v_status = isset($arr['status'])?$arr['status']:0;
	$v_require_approved = isset($arr['require_approved'])?$arr['require_approved']:'0';
	$v_user_approved = isset($arr['user_approved'])?$arr['user_approved']:'';
	$v_user_modified = isset($arr['user_modified'])?$arr['user_modified']:'';
	$v_user_name = isset($arr['user_name'])?$arr['user_name']:'';
	$v_dispatch = isset($arr['dispatch'])?$arr['dispatch']:0;
	$v_tax_1 = isset($arr['tax_1'])?$arr['tax_1']:0;
	$v_tax_2 = isset($arr['tax_2'])?$arr['tax_2']:0;
	$v_tax_3 = isset($arr['tax_3'])?$arr['tax_3']:0;
	$v_dsp_tb_order .= '<td>'.$v_order_id.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_raw_id.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_anvy_id.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_location_id.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_company_id.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_po_number.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_order_type.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_shipping_contact.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_total_order_amount.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_total_discount.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_billing_contact.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_net_order_amount.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_gross_order_amount.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_job_description.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_description.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_notes.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_order_ref.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_sale_rep.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_date_created.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_date_required.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_date_approved.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_date_modified.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_term.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_delivery_method.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_source.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_status.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_require_approved.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_user_approved.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_user_modified.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_user_name.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_dispatch.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_tax_1.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_tax_2.'</td>';
	$v_dsp_tb_order .= '<td>'.$v_tax_3.'</td>';
	$v_dsp_tb_order .= '</tr>';
}
$v_dsp_tb_order .= '</table>';
?>