function create_data(){
    var json;
    json = {
        "version": "2.0",
        "canvases": [
            {
                "texts": [
                    {
                        "body": "",
                        "name": "company_name",
                        "title": "Company Name",
                        "left": 0.86,
                        "top": 0.325,
                        "width": 2.45,
                        "gravity": "west",
                        "preset_text": "Company%20Name",
                        "pointsize": 12,
                        "font": "Arial",
                        "color": "010101",
                        "bold": true,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.27,
                        "show_preset": true,
                        "show_in_panel": true,
                        "hide_in_panel": false,
                        "fit_to_box": false
                    },
                    {
                        "body": "",
                        "name": "slogan",
                        "title": "Slogan",
                        "left": 0.86,
                        "top": 0.535,
                        "width": 2.45,
                        "gravity": "west",
                        "preset_text": "Slogan",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_in_panel": true,
                        "show_preset": true,
                        "hide_in_panel": false,
                        "fit_to_box": false
                    },
                    {
                        "body": "",
                        "name": "name",
                        "title": "Your Name",
                        "left": 0.34,
                        "top": 0.725,
                        "width": 3,
                        "gravity": "west",
                        "preset_text": "Your%20Name",
                        "pointsize": 9,
                        "font": "Arial",
                        "color": "010101",
                        "bold": true,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.2,
                        "show_in_panel": true,
                        "show_preset": true,
                        "hide_in_panel": false,
                        "fit_to_box": false
                    },
                    {
                        "body": "",
                        "name": "job_title",
                        "title": "Job Title",
                        "left": 0.34,
                        "top": 0.87,
                        "width": 3,
                        "gravity": "west",
                        "preset_text": "Job%20Title",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_in_panel": true,
                        "show_preset": true,
                        "hide_in_panel": false,
                        "fit_to_box": false
                    },
                    {
                        "body": "",
                        "name": "phone",
                        "title": "Phone No",
                        "left": 0.35,
                        "top": 1.095,
                        "width": 1.86,
                        "gravity": "west",
                        "preset_text": "P: 800.555.1234",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_in_panel": true,
                        "show_preset": true,
                        "hide_in_panel": false,
                        "fit_to_box": false
                    },
                    {
                        "body": "",
                        "name": "fax",
                        "title": "Fax No",
                        "left": 0.355,
                        "top": 1.225,
                        "width": 1.86,
                        "gravity": "west",
                        "preset_text": "F: 800.555.2345",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_in_panel": true,
                        "show_preset": true,
                        "hide_in_panel": false,
                        "fit_to_box": false
                    },
                    {
                        "body": "",
                        "name": "email",
                        "title": "E-mail Address",
                        "left": 0.35,
                        "top": 1.355,
                        "width": 1.86,
                        "gravity": "west",
                        "preset_text": "E: name@company.com",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_in_panel": true,
                        "show_preset": true,
                        "hide_in_panel": false,
                        "fit_to_box": false
                    },
                    {
                        "body": "",
                        "name": "address_line_1",
                        "title": "Address Line 1",
                        "left": 0.345,
                        "top": 1.48,
                        "width": 1.86,
                        "gravity": "west",
                        "preset_text": "12345 Main Street",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_in_panel": true,
                        "show_preset": true,
                        "hide_in_panel": false,
                        "fit_to_box": false
                    },
                    {
                        "body": "",
                        "name": "address_line_2",
                        "title": "Address Line 2",
                        "left": 0.35,
                        "top": 1.61,
                        "width": 1.86,
                        "gravity": "west",
                        "preset_text": "City Name, State 98765",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_in_panel": true,
                        "show_preset": true,
                        "hide_in_panel": false,
                        "fit_to_box": false
                    },
                    {
                        "body": "",
                        "name": "web_address",
                        "title": "Web Address",
                        "left": 0.35,
                        "top": 1.74,
                        "width": 1.86,
                        "gravity": "west",
                        "preset_text": "www.companyname.com",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_in_panel": true,
                        "show_preset": true,
                        "hide_in_panel": false,
                        "fit_to_box": false
                    }
                ],
                "images": [
                    /*
                    {
                        "image_id": "10000010",
                        "name": "image_80737",
                        "zindex": 300,
                        "rotation": 0,
                        "fixedratio": false,
                        "noselect": true,
                        "noresize": false,
                        "border_color": "FFFFFF",
                        "border_width": 0,
                        "width": 3.745,
                        "height": 1.43,
                        "left": -0.02,
                        "top": 0.795,
                        "svg_id": 6,
                        "svg_colors": ["ffc815#0"],
                        "crop": true,
                        "cropWidth": 1,
                        "cropHeight": 0.5921,
                        "cropTop": 0,
                        "cropLeft": 0,
                        "placeholder": false,
                        "unmovable": true,
                        "type": "mask"
                    },
                    {
                        "image_id": "10000406",
                        "name": "image_27638",
                        "zindex": 301,
                        "rotation": 0,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_color": "FFFFFF",
                        "border_width": 0,
                        "width": 0.6,
                        "height": 0.56,
                        "left": 2.66,
                        "top": 1.225,
                        "svg_id": 119,
                        "svg_colors": ["ffc815#2", "FFFFFF", "ffffff#4"],
                        "crop": false,
                        "type": "mask",
                        "placeholder": "",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    },
                    */
                    {
                        "image_id": "10000028",
                        "name": "logo",
                        "zindex": 200,
                        "rotation": 0,
                        "fixedratio": true,
                        "width": 0.4,
                        "height": 0.4,
                        "left": 0.35,
                        "top": 0.325,
                        "crop": false,
                        "placeholder": "fitter",
                        "type": "regular",
                        "noprint": true,
                        "noselect": false,
                        "unmovable": false,
                        "noresize": false,
                        "invisible": false,
                        "uploader": false
                    }
                ],
                "width": 3.68,
                "height": 2.1799999999999997,
                "name": "Front Side",
                "bleed": 0.125,
                "droppable": true,
                "bg_color": "ffffff"
            },
            {
                "texts": [
                    {
                        "body": "Your%20Appointment",
                        "name": "user_text_1",
                        "title": "Enter text here",
                        "left": 0.39,
                        "top": 0.27,
                        "width": 2.9,
                        "gravity": "center",
                        "preset_text": "New Text Box...",
                        "pointsize": 10,
                        "font": "Arial",
                        "color": "010101",
                        "bold": true,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.225,
                        "hide_in_panel": false,
                        "fit_to_box": false,
                        "show_preset": true
                    },
                    {
                        "body": "has and appointment on",
                        "name": "user_text_2",
                        "title": "Enter text here",
                        "left": 0.845,
                        "top": 0.73,
                        "width": 2.125,
                        "gravity": "center",
                        "preset_text": "New Text Box...",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_preset": true,
                        "hide_in_panel": true,
                        "fit_to_box": false
                    },
                    {
                        "body": "Mon",
                        "name": "user_text_3",
                        "title": "Enter text here",
                        "left": 0.805,
                        "top": 0.945,
                        "width": 0.27,
                        "gravity": "west",
                        "preset_text": "New Text Box...",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_preset": true,
                        "hide_in_panel": true,
                        "fit_to_box": false
                    },
                    {
                        "body": "Tue",
                        "name": "user_text_4",
                        "title": "Enter text here",
                        "left": 1.3,
                        "top": 0.945,
                        "width": 0.27,
                        "gravity": "west",
                        "preset_text": "New Text Box...",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_preset": true,
                        "hide_in_panel": true,
                        "fit_to_box": false
                    },
                    {
                        "body": "Wed",
                        "name": "user_text_5",
                        "title": "Enter text here",
                        "left": 1.845,
                        "top": 0.945,
                        "width": 0.27,
                        "gravity": "west",
                        "preset_text": "New Text Box...",
                        "pointsize": 8,
                        "font": "Verdana",
                        "color": "010101",
                        "bold": false,
                        "italic": false,
                        "rotation": 0,
                        "height": 0.18,
                        "show_preset": true,
                        "hide_in_panel": true,
                        "fit_to_box": false
                    },
                    {
                        "body": "Thu", "name": "user_text_6", "title": "Enter text here",
                        "left": 2.355, "top": 0.945, "width": 0.27, "gravity": "west",
                        "preset_text": "New Text Box...", "pointsize": 8, "font": "Verdana",
                        "color": "010101", "bold": false, "italic": false, "rotation": 0,
                        "height": 0.18, "show_preset": true, "hide_in_panel": true, "fit_to_box": false
                    },
                    {
                        "body": "Fri", "name": "user_text_7", "title": "Enter text here", "left": 2.9, "top": 0.945,
                        "width": 0.27, "gravity": "west", "preset_text": "New Text Box...", "pointsize": 8,
                        "font": "Verdana", "color": "010101", "bold": false, "italic": false, "rotation": 0, "height": 0.18,
                        "show_preset": true, "hide_in_panel": true, "fit_to_box": false
                    },
                    {
                        "body": "At", "name": "user_text_10", "title": "Enter text here", "left": 2.095, "top": 1.3, "width": 0.17,
                        "gravity": "west", "preset_text": "New Text Box...", "pointsize": 8, "font": "Verdana", "color": "010101",
                        "bold": false, "italic": false, "rotation": 0, "height": 0.18, "show_preset": true, "hide_in_panel": true,
                        "fit_to_box": false
                    },
                    {
                        "body": "AM", "name": "user_text_8", "title": "Enter text here", "left": 3.115, "top": 1.155, "width": 0.2,
                        "gravity": "west", "preset_text": "New Text Box...", "pointsize": 8, "font": "Verdana", "color": "010101",
                        "bold": false, "italic": false, "rotation": 0, "height": 0.18, "show_preset": true, "hide_in_panel": true,
                        "fit_to_box": false
                    },
                    {
                        "body": "PM", "name": "user_text_9", "title": "Enter text here", "left": 3.11, "top": 1.315, "width": 0.2,
                        "gravity": "west", "preset_text": "New Text Box...", "pointsize": 8, "font": "Verdana", "color": "010101",
                        "bold": false, "italic": false, "rotation": 0, "height": 0.18, "show_preset": true, "hide_in_panel": true, "fit_to_box": false
                    },
                    {
                        "body": "If you're unable to keep your appointment: Aplease contact us as soon as possible", "name": "user_text_11",
                        "title": "Enter text here", "left": 0.33, "top": 1.52, "width": 3.015, "gravity": "center", "preset_text": "New Text Box...",
                        "pointsize": 8, "font": "Verdana", "color": "010101", "bold": false, "italic": false,
                        "rotation": 0, "height": 0.31, "show_preset": true, "hide_in_panel": false, "fit_to_box": false
                    }
                ],
                "images": [
                    {
                        "zindex": 200,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_width": "1",
                        "border_color": "010101#3",
                        "fill_color": "fdf6bb",
                        "border_stroke": "solid",
                        "shape_type": "hline",
                        "name": "shape_60061",
                        "height": 0.185,
                        "width": 2.8, "left": 0.44,
                        "top": 0.6,
                        "crop": false,
                        "placeholder": "",
                        "type": "regular",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    },
                    {
                        "zindex": 201,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_width": "1",
                        "border_color": "010101#3",
                        "fill_color": "fdf6bb",
                        "border_stroke": "solid",
                        "shape_type": "hline",
                        "name": "shape_60061_990",
                        "height": 0.185,
                        "width": 1.65,
                        "left": 0.405,
                        "top": 1.33,
                        "crop": false,
                        "placeholder": "",
                        "type": "regular",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    },
                    {
                        "zindex": 202,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_width": "1",
                        "border_color": "010101#3",
                        "fill_color": "fdf6bb",
                        "border_stroke": "solid",
                        "shape_type": "hline",
                        "name": "shape_60061_990_306",
                        "height": 0.185,
                        "width": 0.645,
                        "left": 2.26,
                        "top": 1.325,
                        "crop": false,
                        "placeholder": "",
                        "type": "regular",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    },
                    {
                        "zindex": 203,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_width": "0.5",
                        "border_color": "010101#3",
                        "fill_color": "ffffff",
                        "border_stroke": "solid",
                        "shape_type": "rect",
                        "name": "shape_41446",
                        "height": 0.115,
                        "width": 0.115,
                        "left": 2.975,
                        "top": 1.175,
                        "crop": false,
                        "placeholder": "",
                        "type": "regular",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    },
                    {
                        "zindex": 204,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_width": "0.5",
                        "border_color": "010101#3",
                        "fill_color": "ffffff",
                        "border_stroke": "solid",
                        "shape_type": "rect",
                        "name": "shape_41446_644",
                        "height": 0.115,
                        "width": 0.115,
                        "left": 2.975,
                        "top": 1.32,
                        "crop": false,
                        "placeholder": "",
                        "type": "regular",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    },
                    {
                        "zindex": 205,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_width": "0.5",
                        "border_color": "010101#3",
                        "fill_color": "ffffff",
                        "border_stroke": "solid",
                        "shape_type": "rect",
                        "name": "shape_41446_501",
                        "height": 0.115,
                        "width": 0.115,
                        "left": 0.665,
                        "top": 0.975,
                        "crop": false,
                        "placeholder": "",
                        "type": "regular",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    },
                    {
                        "zindex": 206,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_width": "0.5",
                        "border_color": "010101#3",
                        "fill_color": "ffffff",
                        "border_stroke": "solid",
                        "shape_type": "rect",
                        "name": "shape_41446_501_735",
                        "height": 0.115,
                        "width": 0.115,
                        "left": 1.18,
                        "top": 0.975,
                        "crop": false,
                        "placeholder": "",
                        "type": "regular",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    },
                    {
                        "zindex": 207,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_width": "0.5",
                        "border_color": "010101#3",
                        "fill_color": "ffffff",
                        "border_stroke": "solid",
                        "shape_type": "rect",
                        "name": "shape_41446_501_942",
                        "height": 0.115,
                        "width": 0.115,
                        "left": 1.705,
                        "top": 0.975,
                        "crop": false,
                        "placeholder": "",
                        "type": "regular",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    },
                    {
                        "zindex": 208,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_width": "0.5",
                        "border_color": "010101#3",
                        "fill_color": "ffffff",
                        "border_stroke": "solid",
                        "shape_type": "rect",
                        "name": "shape_41446_501_942_329",
                        "height": 0.115,
                        "width": 0.115,
                        "left": 2.225,
                        "top": 0.975,
                        "crop": false,
                        "placeholder": "",
                        "type": "regular",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    },
                    {
                        "zindex": 209,
                        "fixedratio": false,
                        "noselect": false,
                        "noresize": false,
                        "border_width": "0.5",
                        "border_color": "010101#3",
                        "fill_color": "ffffff",
                        "border_stroke": "solid",
                        "shape_type": "rect",
                        "name": "shape_41446_501_942_329_858",
                        "height": 0.115,
                        "width": 0.115,
                        "left": 2.74,
                        "top": 0.975,
                        "crop": false,
                        "placeholder": "",
                        "type": "regular",
                        "noprint": false,
                        "unmovable": false,
                        "invisible": false,
                        "uploader": false
                    }
                ],
                "width": 3.68,
                "height": 2.1799999999999997,
                "name": "Back Side",
                "bleed": 0.125,
                "droppable": true,
                "bg_color": "ffffff"
            }
        ],
        "width": 3.43,
        "height": 1.93,
        "folding": "none",
        "foldingDirection": "vertical",
        "dieCutType": "none",
        "wrap_size": 0,
        "wrap_color": "none",
        "product": "appointmentCard",
        "stockImages": {}
    };
    var images = [
        {
            added_on: "2012-06-05 13:05:23",
            asset_name: "",
            customer_id: "909518",
            delete_flag: "0",
            dpi: 72,
            extension: "svg",
            height: 144,
            id: 10000010,
            is_public: 1,
            is_vector: 1,
            name: "SVG1.svg",
            session_id: "",
            site_code: "YP",
            size: null,
            svg_id: 6,
            visitor_id: null,
            width: 216
        },
        {
            added_on: "2012-06-07 16:02:13",
            asset_name: "",
            customer_id: 909518,
            delete_flag: 1,
            dpi: 72,
            extension: "png",
            height: 288,
            id: 10000028,
            is_public: 1,
            is_vector: 0,
            name: "YourLogo2.png",
            session_id: "",
            site_code: "YP",
            size: null,
            svg_id: null,
            visitor_id: null,
            width: 288
        },
        {
            added_on: "2012-07-05 10:03:59",
            asset_name: "",
            customer_id: 909518,
            delete_flag: 0,
            dpi: 72,
            extension: "svg",
            height: 164,
            id: 10000406,
            is_public: 1,
            is_vector: 1,
            name: "dentistrylogo2.svg",
            session_id: "",
            site_code: "YP",
            size: null,
            svg_id: 119,
            visitor_id: null,
            width: 175
        }
    ];
    var theme = {
        colors: ["ffc815", "000000", "ffc815", "010101", "ffffff", "666666", "ffffff"],
        delete_flag: 1,
        id: 3,
        title: "automotive 1"
    };
    var themes = [{
        delete_flag:0,
        id:84,
        title: "Dental II",
        colors: ["2aa7d3", "067fa9", "9adfef","6d6e71", "c4c4c4", "666666","ffffff"]
    }];
    var data = {
        assigned_to: "2",
        diecut: "none",
        folding: "none",
        fotoliaLicenses: [],
        height: 1.93,
        title:"",
        width: 3.43,
        id: 12630,
        price_markup: 0,
        product_id: 7,
        product_title: "Appointment Cards",
        product_url_code: "appointment+cards",
        set_id: 49,
        set_title: "Clean & Healthy Teeth",
        size_title: "",
        status_id: "4",
        stock_image_cost: 0,
        success:1,
        images: images,
        json: json,
        theme: theme,
        themes: themes
    };
    return data;
}