// JavaScript Document
function reset_view(){
	view = {
	DesignToolHeight: 850,
	DesignToolWidth: 955,
	baseDpi: 19.791666666666668,
	callbacks: [],
	canvasShiftX: 21.5,
	canvasShiftY: 2,
	clipboard: [],
	currentPage: 0,
	customFontSizes: [],
	defaultFontSize: 98,
	designName:	"Text & Logo",
	dpi:	19,
	dragLockX: 	true,
	dragLockY: 	true,
	duplicate: 	false,
	fontSizes: 	[],
	fotoliaLicenses: {},
	hSnapBuffer: [],
	imageInfo:{ 10000028: { uploadWidth:288, uploadHeight:288, is_vector:0, is_public:1}},	
	isDesignSaved:true,
	jdesign: { 
		version:"2.0", 
		canvases:[ { 
					texts:[
						{
							body:"",
							bold:true,
							color: "000000",
							fit_to_box: true,
							font: "Arial",
							gravity: "center",
							height: 6.947368421052632,
							hide_in_panel: false,
							italic: false,
							left: 2.421,
							name: "user_text_68169",
							pointsize: 300,
							preset_text: "Your%20Message",	
							rotation:0,	
							show_preset:true	,
							title: "Enter text here"	,
							top:3.368	,
							width:43.21052631578947							
						},
						{
							body: "",
							bold: true,
							color: "010101#2",
							fit_to_box: false,
							font: "Arial",
							gravity: "west",
							height: 4.684210526315789,
							hide_in_panel: false,
							italic: false,
							left: 11.632,
							name: "company_name",
							pointsize:210,
							preset_text: "Company%20Name",
							rotation: 0,
							show_in_panel: true,
							show_preset: true,
							title :"Company Name",
							top: 12.947,
							width: 34						
						},
						{
							body: "",
							bold: true,
							color: "3b3b3b#1",
							fit_to_box: false,
							font: "Arial",
							gravity: "west",
							height: 4,
							hide_in_panel: false,
							italic: false,
							left: 11.632,
							name: "phone",
							pointsize:180,
							preset_text: "Phone",
							rotation: 0,
							show_in_panel: true,
							show_preset: true,
							title :"Phone No.",
							top: 16.421,
							width: 34						
						},
						{
							body: "",
							bold: true,
							color: "3b3b3b#1",
							fit_to_box: false,
							font: "Arial",
							gravity: "west",
							height: 2.6842105263157894,
							hide_in_panel: false,
							italic: false,
							left: 11.632,
							name: "web_address",
							pointsize:120,
							preset_text: "www.yourcompany.com",
							rotation: 0,
							show_in_panel: true,
							show_preset: true,
							title :"Web Address",
							top: 16.421,
							width: 34						
						}
						
					], 
					images:[ {
								image_id:"10000028", 
								name:"logo", 
								zindex:200,
								border_color: "FFFFFF",
								border_width:0,
								crop: false,
								fixedratio: true,
								height: 	6.842,
								left:	3.316,
								noprint: true,
								noresize: false,
								noselect: false,
								placeholder: "fitter",
								rotation: 0,
								top: 14.421,
								width:6.842
						}], 
					width:48, 
					bg_color: "FFFFFF",
					bleed:	0,
					droppable: true,
					height:24,
					name: "Front Side"					
				}
				], 
		width:48, 
		dieCutType:"none",
		folding:"none",
		foldingDirection:"vertical",
		height:24,
		product:"vinylBanner",	
		stockImages:{},
		wrap_size:0	
	},
	labelSize: 0,
	loadingTimer:14,
	mouseDownX :1393, 
	mouseDownY: 127,
	mousePosX: 796,
	mousePosY: 284,
	mouseUpX: 1393,
	mouseUpY: 127,
	outdatedJdesign: false,
	profileEQ: 
		{ 
			id:"0", 
			description:"UPrinting.com", 
			show_text_panel:0, 
			show_ruler: 0
		},
	showAdvancedToolbar: true,
	showBleed: false,
	showGrid: false,
	showRuler: true,
	showSafeZone: false,
	snapEnabled: true,
	stateIndex: 0,
	states: [
			{ 
				page:0, 
				design:
					{
						dieCutType:"none",
						folding: "none",
						foldingDirection:"vertical",
						height: 24,
						product: "vinylBanner",
						stockImages: {},
						version: "2.0",
						width: 48,
						wrap_size: 0,
				canvases:[ { 
					texts:[
						{
							body:"",
							bold:true,
							color: "000000",
							fit_to_box: true,
							font: "Arial",
							gravity: "center",
							height: 6.947368421052632,
							hide_in_panel: false,
							italic: false,
							left: 2.421,
							name: "user_text_68169",
							pointsize: 300,
							preset_text: "Your%20Message",	
							rotation:0,	
							show_preset:true	,
							title: "Enter text here"	,
							top:3.368	,
							width:43.21052631578947							
						},
						{
							body: "",
							bold: true,
							color: "010101#2",
							fit_to_box: false,
							font: "Arial",
							gravity: "west",
							height: 4.684210526315789,
							hide_in_panel: true,
							italic: false,
							left: 11.632,
							name: "company_name",
							pointsize:210,
							preset_text: "Company%20Name",
							rotation: 0,
							//show_in_panel: true,
							show_preset: true,
							title :"Company Name",
							top: 12.947,
							width: 34						
						},
						{
							body: "",
							bold: true,
							color: "3b3b3b#1",
							fit_to_box: false,
							font: "Arial",
							gravity: "west",
							height: 4,
							hide_in_panel: false,
							italic: false,
							left: 11.632,
							name: "phone",
							pointsize:180,
							preset_text: "Phone",
							rotation: 0,
							show_in_panel: true,
							show_preset: true,
							title :"Phone No.",
							top: 16.421,
							width: 34						
						},
						{
							body: "",
							bold: true,
							color: "3b3b3b#1",
							fit_to_box: false,
							font: "Arial",
							gravity: "west",
							height: 2.6842105263157894,
							hide_in_panel: false,
							italic: false,
							left: 11.632,
							name: "web_address",
							pointsize:120,
							preset_text: "www.yourcompany.com",
							rotation: 0,
							show_in_panel: true,
							show_preset: true,
							title :"Web Address",
							top: 16.421,
							width: 34						
						}
						
					], 
					images:[ {
								image_id:"10000028", 
								name:"logo", 
								zindex:200,
								border_color: "FFFFFF",
								border_width:0,
								crop: false,
								fixedratio: true,
								height: 	6.842,
								left:	3.316,
								noprint: true,
								noresize: false,
								noselect: false,
								placeholder: "fitter",
								rotation: 0,
								top: 14.421,
								width:6.842
						}], 
					width:48, 
					bg_color: "FFFFFF",
					bleed:	0,
					droppable: true,
					height:24,
					name: "Front Side"					
				}
				]

			}
		}
	],
	templateId: 12636,
	textInsertCount: 0,
	themes: [],
	userImages: [],
	userTexts: [],
	userWarned: false,
	vSnapBuffer: [],
	zoomLevel:0
};
}
function create_data(){
	var images = [{
		added_on: "2012-06-07 16:02:13",
		asset_name: "",
		customer_id: 909518,
		delete_flag: 1,
		dpi: 72,
		extension: "png",
		height: 288,
		id: 10000028,
		is_public: 1,
		is_vector: 0,
		name: "YourLogo2.png",
		session_id: "",
		site_code: "YP",
		size: null,
		svg_id: null,
		visitor_id: null,
		width: 288		
	}];
	var json = {
		version:"2.0", 
		canvases:[ { 
					texts:[
						{
							body:"Your Message",
							bold:true,
							color: "000000",
							fit_to_box: true,
							font: "Arial",
							gravity: "center",
							height: 6.947368421052632,
							hide_in_panel: false,
							italic: false,
							left: 2.421,
							name: "your_message",
							pointsize: 300,
							preset_text: "Your Message",
							rotation:0,	
							show_preset:true	,
							title: "Enter text here"	,
							top:3.368	,
							width:43.21052631578947							
						},
						{
							body: "Company Name",
							bold: true,
							color: "0006FF",
							fit_to_box: false,
							font: "Arial",
							gravity: "west",
							height: 4.684210526315789,
							hide_in_panel: false,
							italic: false,
							left: 11.632,
							name: "company_name",
							pointsize:210,
							preset_text: "Company Name",
							rotation: 0,
							show_in_panel: true,
							show_preset: true,
							title :"Company Name",
							top: 8.947,
							width: 34						
						},
						{
							body: "Phone",
							bold: true,
							color: "AA6600",
							fit_to_box: false,
							font: "Arial",
							gravity: "west",
							height: 4,
							hide_in_panel: false,
							italic: false,
							left: 11.632,
							name: "phone",
							pointsize:180,
							preset_text: "Phone",
							rotation: 0,
							show_in_panel: true,
							show_preset: true,
							title :"Phone No.",
							top: 12.421,
							width: 34						
						},
						{
							body: "Web Address",
							bold: true,
							color: "ba2960",
							fit_to_box: false,
							font: "Arial",
							gravity: "west",
							height: 2.6842105263157894,
							hide_in_panel: false,
							italic: false,
							left: 11.632,
							name: "web_address",
							pointsize:120,
							preset_text: "www.yourcompany.com",
							rotation: 0,
							show_in_panel: true,
							show_preset: true,
							title :"Web Address",
							top: 16.421,
							width: 34						
						}
						
					], 
					images:[ {
								image_id:"10000028", 
								name:"logo", 
								zindex:200,
								border_color: "FFFFFF",
								border_width:0,
								crop: false,
								fixedratio: true,
								height: 	6.842,
								left:	3.316,
								noprint: true,
								noresize: false,
								noselect: false,
								placeholder: "fitter",
								rotation: 0,
								top: 14.421,
								width:6.842
						}], 
					width:48, 
					bg_color: "FFFFFF",
					bleed:	0,
					droppable: true,
					height:24,
					name: "Front Side"					
				}
				], 
			width:48, 
			dieCutType:"none",
			folding:"none",
			foldingDirection:"vertical",
			height:24,
			product:"vinylBanner",	
			stockImages:{},
			wrap_size:0	
		};
	var data = {
		assigned_to: 6,
		diecut: "none",
		folding: "none",
		fotoliaLicenses: [],
		height: 24,
		id: 12636,
		price_markup: 0,
		product_id: 20,
		product_title: "Banners",
		product_url_code: "banners",
		set_id: 29,
		set_title: "Text & Logo",
		size_title: "",
		status_id: 4,
		stock_image_cost: 0,
		success: 1,
		themes: [],
		title: "",
		width: 48,		
		images: images,
		json: json
	};
	return data;
}